language: node_js
node_js:
  - node
cache:
  apt: true
  directories:
    - node_modules
env:
  - SERVER_IP_ADDRESS=148.70.230.51
addons:
ssh_known_hosts:
  - 148.70.230.51
script:
  - npm install
after_script:
  - npm run build