language: node_js
node_js:
- node
cache:
  apt: true
  directories:
  - node_modules
env:
- SERVER_IP_ADDRESS=148.70.230.51
addons: 
ssh_known_hosts:
- 148.70.230.51
script:
- npm install
after_script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
-in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@47.98.99.250 pwd